name: Update asyncapi when async-core version changes

on:
  push:
    branches: [ "main" ]
#    paths:
#      - "pom.xml"   # следим только за изменением pom.xml
  workflow_dispatch:

jobs:
  update-asyncapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout async-core
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # нужно минимум 2, чтобы был HEAD^

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Extract new async-core version
        id: core-version
        run: |
          NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get previous version
        id: prev-version
        run: |
          git show HEAD^:pom.xml > prev-pom.xml
          PREV_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f prev-pom.xml)
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

      - name: Check if version changed
        run: |
          if [ "${NEW_VERSION}" = "${PREV_VERSION}" ]; then
            echo "Version did not change (${NEW_VERSION}), skipping..."
            exit 78
          else
            echo "Version changed: ${PREV_VERSION} -> ${NEW_VERSION}"
          fi

      - name: Install async-core to local repo
        run: mvn -B install

      - name: Checkout asyncapi repository
        uses: actions/checkout@v4
        with:
          repository: dred22/asyncapi
          token: ${{ secrets.DEV_TOKEN }}
          path: asyncapi

      - name: Update service-a and service-b parent versions
        working-directory: asyncapi
        run: |
          sed -i "0,/<version>.*<\/version>/s//<version>${NEW_VERSION}<\/version>/" service-a/pom.xml
          sed -i "0,/<version>.*<\/version>/s//<version>${NEW_VERSION}<\/version>/" service-b/pom.xml


      - name: Build asyncapi project
        working-directory: asyncapi
        run: mvn -B clean verify

      - name: Commit and push changes
        working-directory: asyncapi
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "jhabitey@gmail.com"
          git add service-a/pom.xml service-b/pom.xml
          git commit -m "chore: bump async-core parent to version ${NEW_VERSION}" || echo "No changes to commit"
          git push
